import { useState, useEffect, useMemo } from 'react';
import {
  ScatterChart,
  Scatter,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  ZAxis,
  Line,
  ComposedChart,
  Bar,
} from 'recharts';
import { Card, Button } from '../../../components/ui';
import { DatasetInfo } from '../../../components/mining/DatasetInfo';
import { InputOutputGuide } from '../../../components/mining/InputOutputGuide';
import { PipelineDiagram } from '../../../components/mining/PipelineDiagram';
import { BestMethodCard } from '../../../components/mining/BestMethodCard';
import { ModelComparisonTable } from '../../../components/mining/ModelComparisonTable';
import { loadDataset } from '../../../services/tarriDataService';
import { getDatasetMeta } from '../../../services/mining/dataAggregation';
import {
  runClusteringComparison,
  formatFeatureLabel,
} from '../../../services/mining/clustering';
import type { TarriRecord } from '../../../types/dataset';
import type {
  ClusteringComparisonResult,
  ClusteringResult,
  DatasetMeta,
  OrderAggregatedRecord,
  ModelComparisonRow,
} from '../../../types/mining';

const CLUSTERING_FEATURE_OPTIONS: { key: keyof OrderAggregatedRecord; label: string; desc: string }[] = [
  { key: 'totalQuantity', label: 'Total Quantity', desc: 'Total food portions ordered in basket' },
  { key: 'totalGrossSales', label: 'Total Gross Sales (£)', desc: 'Total monetary revenue of the order' },
  { key: 'totalEstProfit', label: 'Total Est. Profit (£)', desc: 'Net gross profit generated by order' },
  { key: 'lineItemCount', label: 'Number of Line Items', desc: 'Distinct menu dishes in basket' },
  { key: 'totalEstCost', label: 'Total Est. Cost (£)', desc: 'Cost of goods for order' },
  { key: 'avgPricePerItem', label: 'Average Price Per Item (£)', desc: 'Mean price point of items in basket' },
];

const CLUSTER_COLORS = ['#B45309', '#0284C7', '#059669', '#7C3AED', '#DC2626', '#475569'];

export function ClusteringAnalysis() {
  const [records, setRecords] = useState<TarriRecord[]>([]);
  const [meta, setMeta] = useState<DatasetMeta | null>(null);
  const [isLoadingData, setIsLoadingData] = useState<boolean>(true);

  // Configuration
  const [selectedFeatures, setSelectedFeatures] = useState<(keyof OrderAggregatedRecord)[]>([
    'totalQuantity',
    'totalGrossSales',
    'totalEstProfit',
    'lineItemCount',
  ]);

  // Scatter visualization axis selectors
  const [xAxisKey, setXAxisKey] = useState<string>('totalGrossSales');
  const [yAxisKey, setYAxisKey] = useState<string>('totalQuantity');

  // Execution state
  const [isClustering, setIsClustering] = useState<boolean>(false);
  const [comparisonResult, setComparisonResult] = useState<ClusteringComparisonResult | null>(null);
  const [inspectedK, setInspectedK] = useState<number | null>(null);

  useEffect(() => {
    loadDataset()
      .then((data) => {
        setRecords(data);
        setMeta(getDatasetMeta(data));
        setIsLoadingData(false);
      })
      .catch((err) => {
        console.error('Failed to load dataset for clustering', err);
        setIsLoadingData(false);
      });
  }, []);

  const toggleFeature = (feat: keyof OrderAggregatedRecord) => {
    if (selectedFeatures.includes(feat)) {
      if (selectedFeatures.length > 2) {
        setSelectedFeatures(selectedFeatures.filter((f) => f !== feat));
      }
    } else {
      setSelectedFeatures([...selectedFeatures, feat]);
    }
  };

  const handleRunAnalysis = () => {
    if (records.length === 0) return;
    setIsClustering(true);

    setTimeout(() => {
      try {
        const comp = runClusteringComparison(records, {
          selectedFeatures,
          maxIterations: 50,
        });
        setComparisonResult(comp);
        setInspectedK(comp.recommendedK);
      } catch (err) {
        console.error('Clustering comparison error', err);
      } finally {
        setIsClustering(false);
      }
    }, 150);
  };

  // Active clustering result being viewed
  const activeResult: ClusteringResult | null = useMemo(() => {
    if (!comparisonResult) return null;
    const kToView = inspectedK || comparisonResult.recommendedK;
    return comparisonResult.allResults[kToView] || comparisonResult.activeResult;
  }, [comparisonResult, inspectedK]);

  // Transform K evaluations into ModelComparisonRows
  const kComparisonRows: ModelComparisonRow[] = useMemo(() => {
    if (!comparisonResult) return [];
    return comparisonResult.kEvaluations.map((row) => ({
      modelName: `K = ${row.k} Clusters`,
      isRecommended: row.isRecommended,
      metrics: {
        'Silhouette Score': row.silhouetteScore.toFixed(3),
        'Inertia (WCSS)': Math.round(row.inertia).toLocaleString('en-GB'),
        'Cluster Count': row.clusters,
      },
      badge: row.isRecommended ? 'Recommended' : undefined,
      notes: row.interpretation,
    }));
  }, [comparisonResult]);

  // Chart data for Silhouette and Elbow curves
  const kChartData = useMemo(() => {
    if (!comparisonResult) return [];
    return comparisonResult.kEvaluations.map((row) => ({
      name: `K=${row.k}`,
      k: row.k,
      silhouette: row.silhouetteScore,
      inertia: Math.round(row.inertia),
      isRecommended: row.isRecommended,
    }));
  }, [comparisonResult]);

  // Group scatter points by cluster
  const clusteredScatterSeries = useMemo(() => {
    if (!activeResult) return [];
    const seriesMap = new Map<number, typeof activeResult.scatterPoints>();

    for (let c = 1; c <= activeResult.k; c++) {
      seriesMap.set(c, []);
    }

    for (const pt of activeResult.scatterPoints) {
      seriesMap.get(pt.clusterId)?.push(pt);
    }

    return Array.from(seriesMap.entries()).map(([clusterId, points]) => ({
      clusterId,
      name: `Cluster ${clusterId}`,
      color: CLUSTER_COLORS[(clusterId - 1) % CLUSTER_COLORS.length],
      points,
    }));
  }, [activeResult]);

  const pipelineStages = [
    'Order Aggregation (1,408 Baskets)',
    'Z-Score Standardization: Applied',
    'Candidate Evaluations (K=2..6)',
    'Silhouette Score & Inertia Computation',
    'Data-Driven Best K Selection',
  ];

  return (
    <div className="w-full space-y-6 min-w-0">
      {/* 1. Header with Standardization Badge */}
      <div className="border-b border-neutral-100 pb-5 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-semibold text-neutral-800 tracking-tight">
            Order Clustering & Automatic K Evaluation
          </h1>
          <p className="mt-1 text-sm text-neutral-500">
            Unsupervised order-level customer segmentation evaluating K=2 through K=6 via Silhouette Score and Inertia.
          </p>
        </div>
        <div className="flex items-center gap-2 self-start sm:self-auto">
          <span className="text-xs font-mono bg-neutral-100 text-neutral-700 px-3 py-1 rounded border border-neutral-200">
            Level: 1,408 Unique Orders
          </span>
          <span className="text-xs font-mono bg-blue-50 text-blue-700 px-3 py-1 rounded border border-blue-200">
            Standardization: Applied (Z-Score)
          </span>
        </div>
      </div>

      {/* 2. Dataset Information */}
      {meta && <DatasetInfo meta={meta} levelLabel="Unique Order Level (1,408 Orders)" />}

      {/* 3. Input -> Output Guide */}
      <InputOutputGuide
        input={selectedFeatures.map(formatFeatureLabel).join(', ') || 'Selected features'}
        modelsTested="K-Means Partitions for K = 2, 3, 4, 5, 6"
        selectionCriteria="Highest Silhouette Score (Cluster Cohesion vs. Separation)"
        output="Optimized Cluster Profiles & Order Archetypes"
      />

      {/* 4. Configuration Area */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Configuration Form */}
        <div className="lg:col-span-5 space-y-4">
          <Card className="border border-neutral-100 bg-white space-y-4">
            <div className="flex items-center justify-between pb-2 border-b border-neutral-100">
              <h3 className="text-sm font-semibold text-neutral-800">
                Clustering Configuration
              </h3>
              <span className="text-xs text-neutral-400">
                K=2 through 6 evaluated
              </span>
            </div>

            {/* Feature Selection Checkboxes */}
            <div>
              <div className="flex justify-between items-center mb-1">
                <label className="text-xs font-semibold text-neutral-700">
                  Order-Level Features (Standardized)
                </label>
                <span className="text-[11px] text-neutral-400">
                  {selectedFeatures.length} selected (min 2)
                </span>
              </div>
              <p className="text-[11px] text-neutral-400 mb-2">
                Features aggregated at order level. OrderID is strictly excluded.
              </p>

              <div className="space-y-1.5">
                {CLUSTERING_FEATURE_OPTIONS.map((feat) => {
                  const isSelected = selectedFeatures.includes(feat.key);
                  return (
                    <label
                      key={feat.key}
                      className={`flex items-start justify-between p-2 rounded border text-xs cursor-pointer transition-colors ${
                        isSelected
                          ? 'bg-accent/5 border-accent/40 text-neutral-800 font-medium'
                          : 'bg-white border-neutral-200 text-neutral-600 hover:bg-neutral-50'
                      }`}
                    >
                      <div className="flex items-start gap-2">
                        <input
                          type="checkbox"
                          checked={isSelected}
                          onChange={() => toggleFeature(feat.key)}
                          className="mt-0.5 rounded border-neutral-300 text-accent focus:ring-0"
                        />
                        <div>
                          <span>{feat.label}</span>
                          <p className="text-[10px] text-neutral-400 font-normal">
                            {feat.desc}
                          </p>
                        </div>
                      </div>
                    </label>
                  );
                })}
              </div>
            </div>

            {/* Run Button */}
            <Button
              onClick={handleRunAnalysis}
              disabled={isClustering || isLoadingData || selectedFeatures.length < 2}
              className="w-full bg-accent hover:bg-accent/90 text-white font-medium text-xs py-2.5"
            >
              {isClustering ? 'Evaluating K=2 to K=6...' : 'Run Analysis & Evaluate K=2..6'}
            </Button>
          </Card>
        </div>

        {/* Right: Pipeline Stages & Methodology */}
        <div className="lg:col-span-7 space-y-4">
          <PipelineDiagram stages={pipelineStages} activeStage={comparisonResult ? 4 : 0} />

          <Card className="border border-neutral-100 bg-white">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-neutral-400 mb-1">
              Methodology & Academic Rigor
            </h4>
            <h3 className="text-sm font-semibold text-neutral-800 mb-2">
              Objective Determination of Cluster Count (K)
            </h3>
            <p className="text-xs text-neutral-600 leading-relaxed mb-3">
              K-Means is an unsupervised clustering algorithm that minimizes intra-cluster Euclidean distances. Rather than guessing an arbitrary K, this module runs K-Means from K=2 through K=6 and calculates the <strong>Silhouette Score</strong> for each candidate.
            </p>
            <div className="p-3 bg-neutral-50 rounded-lg border border-neutral-100 text-[11px] text-neutral-600 space-y-1.5">
              <div>
                <strong>Silhouette Score:</strong> Measures how similar an order is to its assigned cluster relative to the nearest alternative cluster (ranges from -1 to +1). Values closer to +1 represent dense, well-isolated clusters.
              </div>
              <div>
                <strong>Inertia (Within-Cluster Sum of Squares):</strong> Measures compactness. Note: Inertia always decreases as K increases; therefore, minimum inertia alone is never used to choose K.
              </div>
            </div>
          </Card>
        </div>
      </div>

      {/* 5. Results & Comparative Ledger */}
      {comparisonResult && activeResult && (
        <div className="space-y-6 pt-4 border-t border-neutral-200">
          {/* A. Universal Best Method Card */}
          <BestMethodCard
            recommendation={comparisonResult.recommendation}
            moduleType="clustering"
          />

          {/* B. Candidate K Comparison Table */}
          <ModelComparisonTable
            title="Cluster Count Evaluation (K = 2 through 6)"
            subtitle="Calculated on 1,408 standardized order baskets with K-Means++ initialization."
            rows={kComparisonRows}
            selectedModelName={`K = ${activeResult.k} Clusters`}
            onSelectModel={(name) => {
              const match = name.match(/K\s*=\s*(\d+)/);
              if (match) setInspectedK(Number(match[1]));
            }}
          />

          {/* C. Choosing the Number of Clusters (Visual Curve) */}
          <Card className="border border-neutral-100 bg-white">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4 pb-2 border-b border-neutral-100">
              <div>
                <h4 className="text-xs font-semibold text-neutral-800">
                  Choosing the Number of Clusters: Silhouette Score vs. K
                </h4>
                <p className="text-[11px] text-neutral-400">
                  The peak Silhouette Score indicates optimal separation and cohesion.
                </p>
              </div>
              <div className="text-xs text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded border border-emerald-200">
                Optimal Peak: K = {comparisonResult.recommendedK}
              </div>
            </div>

            <div className="h-60 w-full">
              <ResponsiveContainer width="100%" height="100%">
                <ComposedChart
                  data={kChartData}
                  margin={{ top: 10, right: 30, left: 10, bottom: 20 }}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                  <XAxis
                    dataKey="name"
                    tick={{ fontSize: 11 }}
                    label={{
                      value: 'Number of Clusters (K)',
                      position: 'insideBottom',
                      offset: -10,
                      fontSize: 11,
                    }}
                  />
                  <YAxis
                    yAxisId="left"
                    domain={[0, 'auto']}
                    tick={{ fontSize: 11 }}
                    label={{
                      value: 'Silhouette Score',
                      angle: -90,
                      position: 'insideLeft',
                      fontSize: 11,
                    }}
                  />
                  <Tooltip
                    content={({ active, payload }) => {
                      if (active && payload && payload.length) {
                        const d = payload[0].payload;
                        return (
                          <div className="bg-white p-2.5 rounded shadow-lg border border-neutral-200 text-xs">
                            <div className="font-semibold text-neutral-800 mb-1">
                              Configuration: K = {d.k}
                            </div>
                            <div className="text-blue-600 font-medium">
                              Silhouette Score: {d.silhouette.toFixed(3)}
                            </div>
                            <div className="text-neutral-500 text-[11px] mt-0.5">
                              Inertia: {d.inertia.toLocaleString('en-GB')}
                            </div>
                            {d.isRecommended && (
                              <div className="mt-1 text-[10px] text-emerald-700 font-semibold">
                                ★ Recommended Configuration
                              </div>
                            )}
                          </div>
                        );
                      }
                      return null;
                    }}
                  />
                  <Bar
                    yAxisId="left"
                    dataKey="silhouette"
                    fill="#2563eb"
                    fillOpacity={0.7}
                    radius={[4, 4, 0, 0]}
                  />
                  <Line
                    yAxisId="left"
                    type="monotone"
                    dataKey="silhouette"
                    stroke="#1e40af"
                    strokeWidth={2}
                    dot={{ r: 4 }}
                  />
                </ComposedChart>
              </ResponsiveContainer>
            </div>
          </Card>

          {/* Academic Transparency Note */}
          <div className="p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-700">
            <span className="font-semibold text-slate-900">Academic Method Selection: </span>
            {comparisonResult.methodSelectionNotes}
          </div>

          {/* D. Active / Inspected K Detailed Inspection */}
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-base font-semibold text-neutral-800">
                  Detailed Inspection: K = {activeResult.k} Clusters
                </h3>
                <p className="text-xs text-neutral-500">
                  {activeResult.k === comparisonResult.recommendedK
                    ? 'Displaying cluster profiles and scatter coordinates for the recommended configuration.'
                    : 'Displaying diagnostics for the selected candidate K value.'}
                </p>
              </div>
              {activeResult.k === comparisonResult.recommendedK ? (
                <span className="text-xs font-semibold px-2.5 py-1 rounded bg-emerald-50 text-emerald-700 border border-emerald-200">
                  Recommended K Configuration
                </span>
              ) : (
                <button
                  type="button"
                  onClick={() => setInspectedK(comparisonResult.recommendedK)}
                  className="text-xs text-blue-600 hover:underline"
                >
                  Switch back to Recommended (K = {comparisonResult.recommendedK})
                </button>
              )}
            </div>

            {/* Cluster Profile Table */}
            <Card className="border border-neutral-100 bg-white">
              <div className="mb-3">
                <h4 className="text-xs font-semibold text-neutral-800">
                  Cluster Archetype Profiles (Original Business Scale)
                </h4>
                <p className="text-[11px] text-neutral-400">
                  Mean metrics calculated from actual restaurant transactions in each cluster.
                </p>
              </div>

              <div className="overflow-x-auto">
                <table className="w-full text-left text-xs">
                  <thead className="bg-neutral-50 text-neutral-500 font-medium uppercase tracking-wider border-b border-neutral-100">
                    <tr>
                      <th className="px-4 py-2.5">Cluster</th>
                      <th className="px-4 py-2.5 text-right">Orders</th>
                      <th className="px-4 py-2.5 text-right">Share (%)</th>
                      <th className="px-4 py-2.5 text-right">Avg Revenue</th>
                      <th className="px-4 py-2.5 text-right">Avg Profit</th>
                      <th className="px-4 py-2.5 text-right">Avg Items</th>
                      <th className="px-4 py-2.5 text-right">Avg Item Price</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-neutral-100">
                    {activeResult.clusters.map((cl, idx) => (
                      <tr key={cl.clusterId} className="hover:bg-neutral-50/50">
                        <td className="px-4 py-2.5 font-medium text-neutral-800">
                          <span
                            className="inline-block w-2.5 h-2.5 rounded-full mr-2"
                            style={{ backgroundColor: CLUSTER_COLORS[idx % CLUSTER_COLORS.length] }}
                          />
                          {cl.name}
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono text-neutral-800">
                          {cl.orderCount.toLocaleString('en-GB')}
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono text-neutral-800">
                          {cl.percentage.toFixed(1)}%
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono font-semibold text-neutral-800">
                          £{cl.avgRevenue.toFixed(2)}
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono text-neutral-800">
                          £{cl.avgProfit.toFixed(2)}
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono text-neutral-800">
                          {cl.avgItemsPerOrder}
                        </td>
                        <td className="px-4 py-2.5 text-right font-mono text-neutral-800">
                          £{cl.avgPricePerItem.toFixed(2)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </Card>

            {/* 2D Cluster Visualization */}
            <Card className="border border-neutral-100 bg-white">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4 pb-2 border-b border-neutral-100">
                <div>
                  <h4 className="text-xs font-semibold text-neutral-800">
                    2D Order Cluster Visualization
                  </h4>
                  <p className="text-[11px] text-neutral-400">
                    Displaying 300 orders projected onto selectable order-level metric axes.
                  </p>
                </div>

                {/* Axis Selectors */}
                <div className="flex items-center gap-2 text-xs">
                  <div className="flex items-center gap-1">
                    <span className="text-neutral-500 text-[11px]">X:</span>
                    <select
                      value={xAxisKey}
                      onChange={(e) => setXAxisKey(e.target.value)}
                      className="px-2 py-1 rounded border border-neutral-200 bg-white text-neutral-800 text-xs"
                    >
                      {selectedFeatures.map((f) => (
                        <option key={f} value={f}>
                          {formatFeatureLabel(f)}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="flex items-center gap-1">
                    <span className="text-neutral-500 text-[11px]">Y:</span>
                    <select
                      value={yAxisKey}
                      onChange={(e) => setYAxisKey(e.target.value)}
                      className="px-2 py-1 rounded border border-neutral-200 bg-white text-neutral-800 text-xs"
                    >
                      {selectedFeatures.map((f) => (
                        <option key={f} value={f}>
                          {formatFeatureLabel(f)}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>

              <div className="h-72 w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <ScatterChart margin={{ top: 10, right: 20, bottom: 20, left: 10 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                    <XAxis
                      dataKey="x"
                      type="number"
                      name={formatFeatureLabel(xAxisKey)}
                      tick={{ fontSize: 11 }}
                      label={{
                        value: formatFeatureLabel(xAxisKey),
                        position: 'insideBottom',
                        offset: -10,
                        fontSize: 11,
                      }}
                    />
                    <YAxis
                      dataKey="y"
                      type="number"
                      name={formatFeatureLabel(yAxisKey)}
                      tick={{ fontSize: 11 }}
                      label={{
                        value: formatFeatureLabel(yAxisKey),
                        angle: -90,
                        position: 'insideLeft',
                        fontSize: 11,
                      }}
                    />
                    <ZAxis range={[25, 25]} />
                    <Tooltip
                      content={({ active, payload }) => {
                        if (active && payload && payload.length) {
                          const d = payload[0].payload;
                          return (
                            <div className="bg-white p-2.5 rounded shadow-lg border border-neutral-200 text-xs">
                              <div className="font-semibold text-neutral-800 mb-1">
                                Order #{d.orderId}
                              </div>
                              <div className="text-neutral-600">
                                Cluster {d.clusterId}
                              </div>
                              <div className="text-neutral-500 text-[11px] mt-1">
                                Revenue: £{d.tooltipInfo.revenue.toFixed(2)} · Quantity: {d.tooltipInfo.quantity}
                              </div>
                            </div>
                          );
                        }
                        return null;
                      }}
                    />
                    {clusteredScatterSeries.map((series) => (
                      <Scatter
                        key={series.clusterId}
                        name={series.name}
                        data={series.points}
                        fill={series.color}
                        fillOpacity={0.7}
                      />
                    ))}
                  </ScatterChart>
                </ResponsiveContainer>
              </div>
            </Card>

            {/* Factual Archetype Descriptions */}
            <Card className="border border-neutral-100 bg-white">
              <h4 className="text-xs font-semibold text-neutral-800 mb-2">
                Factual Cluster Segment Archetypes (K = {activeResult.k})
              </h4>
              <div className="space-y-2 text-xs text-neutral-600">
                {activeResult.explanation.map((exp, idx) => (
                  <div key={idx} className="flex items-start gap-2 p-2.5 rounded bg-neutral-50 border border-neutral-100/60">
                    <span
                      className="inline-block w-2.5 h-2.5 rounded-full mt-0.5 shrink-0"
                      style={{ backgroundColor: CLUSTER_COLORS[idx % CLUSTER_COLORS.length] }}
                    />
                    <span className="leading-relaxed">{exp}</span>
                  </div>
                ))}
              </div>
            </Card>
          </div>
        </div>
      )}
    </div>
  );
}
